services:
  mysql:
    container_name: 'customerconnect-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=customerconnectdb'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3308:3308'